[username]
format = "[$user]($style)@"
style_user = "bold #5E81AC"
style_root = "bold #5E81AC"
show_always = true 
disabled = true

[hostname]
format = "[$hostname]($style) in "
style = "bold #5E81AC"
trim_at = "-"
ssh_only = false
disabled = true 

[directory]
style = 'bold #d5c4a1'
truncation_length = 0
truncate_to_repo = true
#truncation_symbol = "repo: "

[git_status]
style = "#ebddaa"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[git_state]
style = '#ebddaa'

[git_branch]
style = '#bee4ed'

[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = true


[character]
success_symbol = '[❯](bold #c6aae8)'
error_symbol = '[❯](bold #e38c8f)'
vicmd_symbol = '[❮](bold #b1e3ad)'
